### ISSUE TITLE
LateInitializationError with Slidable.closeOnScroll set to false

### ISSUE THREAD

**Issue by wujek-srujek** [letsar/flutter_slidable#195]
When I create my `Slidable`s with `closeOnScroll: false`, I get this exception:
```
Restarted application in 458ms.
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following LateError was thrown building SlidableItemTile-[<U1wKAjIhH57h2Fc5o7p1>](dependencies:
flutter: [_LocalizationsScope-[GlobalKey#3d2e3], _InheritedTheme]):
flutter: LateInitializationError: Field '_overallMoveController@659109557' has not been initialized.
flutter:
flutter: The relevant error-causing widget was:
flutter:   SlidableItemTile-[<U1wKAjIhH57h2Fc5o7p1>]
[38;5;248mflutter:[39;49m
flutter:
flutter: When the exception was thrown, this was the stack:
[38;5;244mflutter: #0      SlidableState._overallMoveController (package:flutter_slidable/src/widgets/slidable.dart)[39;49m
[38;5;244mflutter: #1      SlidableState.wantKeepAlive[39;49m
[38;5;244mflutter: #2      AutomaticKeepAliveClientMixin.initState[39;49m
[38;5;244mflutter: #3      SlidableState.initState[39;49m
[38;5;244mflutter: #4      StatefulElement._firstBuild[39;49m
[38;5;244mflutter: #5      ComponentElement.mount[39;49m
flutter: ...     Normal element mounting (39 frames)
[38;5;244mflutter: #44     Element.inflateWidget[39;49m
[38;5;244mflutter: #45     Element.updateChild[39;49m
[38;5;244mflutter: #46     SliverMultiBoxAdaptorElement.updateChild[39;49m
[38;5;244mflutter: #47     SliverMultiBoxAdaptorElement.createChild.<anonymous closure>[39;49m
[38;5;244mflutter: #48     BuildOwner.buildScope[39;49m
[38;5;244mflutter: #49     SliverMultiBoxAdaptorElement.createChild[39;49m
[38;5;244mflutter: #50     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure>[39;49m
[38;5;244mflutter: #51     RenderObject.invokeLayoutCallback.<anonymous closure>[39;49m
[38;5;244mflutter: #52     PipelineOwner._enableMutationsToDirtySubtrees[39;49m
[38;5;244mflutter: #53     RenderObject.invokeLayoutCallback[39;49m
[38;5;244mflutter: #54     RenderSliverMultiBoxAdaptor._createOrObtainChild[39;49m
[38;5;244mflutter: #55     RenderSliverMultiBoxAdaptor.addInitialChild[39;49m
[38;5;244mflutter: #56     RenderSliverList.performLayout[39;49m
[38;5;244mflutter: #57     RenderObject.layout[39;49m
[38;5;244mflutter: #58     RenderSliverEdgeInsetsPadding.performLayout[39;49m
[38;5;244mflutter: #59     RenderSliverPadding.performLayout[39;49m
[38;5;244mflutter: #60     RenderObject.layout[39;49m
[38;5;244mflutter: #61     RenderViewportBase.layoutChildSequence[39;49m
[38;5;244mflutter: #62     RenderViewport._attemptLayout[39;49m
[38;5;244mflutter: #63     RenderViewport.performLayout[39;49m
[38;5;244mflutter: #64     RenderObject.layout[39;49m
[38;5;244mflutter: #65     RenderProxyBoxMixin.performLayout[39;49m
[38;5;244mflutter: #66     RenderObject.layout[39;49m
[38;5;244mflutter: #67     RenderProxyBoxMixin.performLayout[39;49m
[38;5;244mflutter: #68     RenderObject.layout[39;49m
[38;5;244mflutter: #69     RenderProxyBoxMixin.performLayout[39;49m
[38;5;244mflutter: #70     RenderObject.layout[39;49m
[38;5;244mflutter: #71     RenderProxyBoxMixin.performLayout[39;49m
[38;5;244mflutter: #72     RenderObject.layout[39;49m
[38;5;244mflutter: #73     RenderProxyBoxMixin.performLayout[39;49m
[38;5;244mflutter: #74     RenderObject.layout[39;49m
[38;5;244mflutter: #75     RenderProxyBoxMixin.performLayout[39;49m
[38;5;244mflutter: #76     RenderObject.layout[39;49m
[38;5;244mflutter: #77     RenderProxyBoxMixin.performLayout[39;49m
[38;5;244mflutter: #78     RenderObject.layout[39;49m
[38;5;244mflutter: #79     RenderProxyBoxMixin.performLayout[39;49m
[38;5;244mflutter: #80     RenderCustomPaint.performLayout[39;49m
[38;5;244mflutter: #81     RenderObject.layout[39;49m
[38;5;244mflutter: #82     RenderProxyBoxMixin.performLayout[39;49m
[38;5;244mflutter: #83     RenderObject.layout[39;49m
[38;5;244mflutter: #84     RenderProxyBoxMixin.performLayout[39;49m
[38;5;244mflutter: #85     RenderObject.layout[39;49m
[38;5;244mflutter: #86     RenderProxyBoxMixin.performLayout[39;49m
[38;5;244mflutter: #87     RenderObject.layout[39;49m
[38;5;244mflutter: #88     RenderProxyBoxMixin.performLayout[39;49m
[38;5;244mflutter: #89     RenderObject.layout[39;49m
[38;5;244mflutter: #90     MultiChildLayoutDelegate.layoutChild[39;49m
[38;5;244mflutter: #91     _ScaffoldLayout.performLayout[39;49m
[38;5;244mflutter: #92     MultiChildLayoutDelegate._callPerformLayout[39;49m
[38;5;244mflutter: #93     RenderCustomMultiChildLayoutBox.performLayout[39;49m
[38;5;244mflutter: #94     RenderObject._layoutWithoutResize[39;49m
[38;5;244mflutter: #95     PipelineOwner.flushLayout[39;49m
[38;5;244mflutter: #96     RendererBinding.drawFrame[39;49m
[38;5;244mflutter: #97     WidgetsBinding.drawFrame[39;49m
[38;5;244mflutter: #98     RendererBinding._handlePersistentFrameCallback[39;49m
[38;5;244mflutter: #99     SchedulerBinding._invokeFrameCallback[39;49m
[38;5;244mflutter: #100    SchedulerBinding.handleDrawFrame[39;49m
[38;5;244mflutter: #101    SchedulerBinding._handleDrawFrame[39;49m
[38;5;244mflutter: #105    _invoke (dart:ui/hooks.dart:161:10)[39;49m
[38;5;244mflutter: #106    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:253:5)[39;49m
[38;5;244mflutter: #107    _drawFrame (dart:ui/hooks.dart:120:31)[39;49m
[38;5;244mflutter: (elided 3 frames from dart:async)[39;49m
```
I'm using version `0.6.0-nullsafety.0`. The `SlidableItemTile` in the stack trace is my widget which internally constructs a `Slidable` at the top level, i.e. the `build` method is;
```dart
  @override
  Widget build(BuildContext context) {
    return Slidable(
      closeOnScroll: false,
      ...
```
I'm not using any delegate nor any controller, just a plain `Slidable` with `closeOnScroll`.

Judging by the line `LateInitializationError: Field '_overallMoveController@659109557' has not been initialized.` and the fact that the `Slidable._overallMoveController` field is a `late final`, this seems to be related to null-safety.

**Comment by rmgit** [comment]
same problem here.
exception with closeOnScroll: false,
fine with closeOnScroll: true,

LateInitializationError: Field '_overallMoveController@809109557' has not been initialized.

When the exception was thrown, this was the stack:
#0      SlidableState._overallMoveController (package:flutter_slidable/src/widgets/slidable.dart)
#1      SlidableState.wantKeepAlive (package:flutter_slidable/src/widgets/slidable.dart:624:8)
#2      AutomaticKeepAliveClientMixin.initState (package:flutter/src/widgets/automatic_keep_alive.dart:381:9)
#3      SlidableState.initState (package:flutter_slidable/src/widgets/slidable.dart:549:11)
#4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4704:57)
...

**Comment by rmgit** [comment]
having gone through the sound null safety upgrade + several further package version upgrades this problems seems to be gone  without changes to the code in this part of the app .

**Comment by ozz-rjq** [comment]
having the same issue

**Comment by rignaneseleo** [comment]
same here. Any fix or workaround?

**Comment by 726D** [comment]
@ozz-rjq @rignaneseleo did you do the full sound null safety upgrade and does the problem persist?

**Comment by wujek-srujek** [comment]
The stack trace explicitly states that there is an `LateInitializationError` *in* the lib, I'm not sure whether upgrading to null safety in your app can fix this. Ass a matter of fact, my app, where the issue was originally observed, was fully migrated.

**Comment by 726D** [comment]
As i think the problem was caused (at least in my case) by the changes in the code base many projects made for sound null safety.
For me the stability/compatibility situaton looks much better now then in April.

i would say that the move to sound null safety in itself will not necessarily solve the problem.
i would say that with the full move to sound null safety you get a lot of updated packages and I would expect that the problem will have vanished afterwards (+ maybe also clean all package / compile caches in android studio)

**Comment by letsar** [comment]
Can you try with the 1.0 version?

**Comment by Praveen-0603** [comment]
Still the same issue when closing the tile with .close()

**Comment by wujek-srujek** [comment]
Tested with 1.2.0, works fine now.
