### ISSUE TITLE
[Bug] - Unhandled Exception: type 'Future<bool?>' is not a subtype of type 'FutureOr<bool>' in type cast

### ISSUE THREAD

**Issue by codespair** [letsar/flutter_slidable#209]
I noticed this issue when upgrading an app to use nullable support, flutter_slidable: ^0.6.0. 

To reproduce: Run the example of this project, slide to right and click archive on item > 8 which uses a confirmation dialog. The error then happens, full-stack error: 

```
E/flutter ( 3752): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: type 'Future<bool?>' is not a subtype of type 'FutureOr<bool>' in type cast
[38;5;248mE/flutter ( 3752): #0      _MyHomePageState._getSlidableWithDelegates.<anonymous closure>.<anonymous closure>[39;49m
[38;5;248mE/flutter ( 3752): #1      _MyHomePageState._getSlidableWithDelegates.<anonymous closure>.<anonymous closure>[39;49m
[38;5;248mE/flutter ( 3752): #2      ClosableSlideAction._handleCloseAfterTap[39;49m
[38;5;248mE/flutter ( 3752): #3      ClosableSlideAction.build.<anonymous closure>[39;49m
[38;5;244mE/flutter ( 3752): #4      _InkResponseState._handleTap[39;49m
[38;5;244mE/flutter ( 3752): #5      GestureRecognizer.invokeCallback[39;49m
[38;5;244mE/flutter ( 3752): #6      TapGestureRecognizer.handleTapUp[39;49m
[38;5;244mE/flutter ( 3752): #7      BaseTapGestureRecognizer._checkUp[39;49m
[38;5;244mE/flutter ( 3752): #8      BaseTapGestureRecognizer.acceptGesture[39;49m
[38;5;244mE/flutter ( 3752): #9      GestureArenaManager.sweep[39;49m
[38;5;244mE/flutter ( 3752): #10     GestureBinding.handleEvent[39;49m
[38;5;244mE/flutter ( 3752): #11     GestureBinding.dispatchEvent[39;49m
[38;5;244mE/flutter ( 3752): #12     RendererBinding.dispatchEvent[39;49m
[38;5;244mE/flutter ( 3752): #13     GestureBinding._handlePointerEventImmediately[39;49m
[38;5;244mE/flutter ( 3752): #14     GestureBinding.handlePointerEvent[39;49m
[38;5;244mE/flutter ( 3752): #15     GestureBinding._flushPointerEventQueue[39;49m
[38;5;244mE/flutter ( 3752): #16     GestureBinding._handlePointerDataPacket[39;49m
[38;5;244mE/flutter ( 3752): #17     _rootRunUnary (dart:async/zone.dart:1370:13)[39;49m
[38;5;244mE/flutter ( 3752): #18     _CustomZone.runUnary (dart:async/zone.dart:1265:19)[39;49m
[38;5;244mE/flutter ( 3752): #19     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)[39;49m
[38;5;244mE/flutter ( 3752): #20     _invoke1 (dart:ui/hooks.dart:180:10)[39;49m
[38;5;244mE/flutter ( 3752): #21     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:276:7)[39;49m
[38;5;244mE/flutter ( 3752): #22     _dispatchPointerDataPacket (dart:ui/hooks.dart:96:31)[39;49m
E/flutter ( 3752):
```

**Comment by codespair** [comment]
Hi @letsar - I have sent a M.R with the fix for the bug and the example.

**Comment by letsar** [comment]
Can you verify if the issue is still in the 1.0? I will not update the 0.6.

**Comment by letsar** [comment]
This thread has been closed since there has not been any response for a while. If you are still experiencing a similar issue, please open a new bug.
