### ISSUE TITLE
Slidable freezes on tab bar only in release mode

### ISSUE THREAD

**Issue by parasthekoder** [letsar/flutter_slidable#25]
### Steps to Reproduce

1. Create a Tab Widget
2. Switch between tabs
3. Now do a slidable.
4. Switch between tabs.
5. Do slidable again and now it freezes.

### Exception 

```
[ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (26409): NoSuchMethodError: The method 'contains' was called on null.
E/flutter (26409): Receiver: null
E/flutter (26409): Tried calling: contains()
E/flutter (26409): #0      RenderBox.hitTest (package:flutter/src/rendering/box.dart:1862)
E/flutter (26409): #1      _RenderSliverMultiBoxAdaptor&RenderSliver&ContainerRenderObjectMixin&RenderSliverHelpers.hitTestBoxChild (package:flutter/src/rendering/sliver.dart:1475)
E/flutter (26409): #2      RenderSliverMultiBoxAdaptor.hitTestChildren (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:455)
E/flutter (26409): #3      RenderSliver.hitTest (package:flutter/src/rendering/sliver.dart:1137)
E/flutter (26409): #4      RenderSliverPadding.hitTestChildren (package:flutter/src/rendering/sliver_padding.dart:266)
E/flutter (26409): #5      RenderSliver.hitTest (package:flutter/src/rendering/sliver.dart:1137)
E/flutter (26409): #6      RenderViewportBase.hitTestChildren (package:flutter/src/rendering/viewport.dart:503)
E/flutter (26409): #7      RenderBox.hitTest (package:flutter/src/rendering/box.dart:1863)
E/flutter (26409): #8      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:118)
E/flutter (26409): #9      RenderBox.hitTest (package:flutter/src/rendering/box.dart:1863)
E/flutter (26409): #10     RenderIgnorePointer.hitTest (package:flutter/src/rendering/proxy_box.dart:2727)
E/flutter (26409): #11     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:118)
E/flutter (26409): #12     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1863)
E/flutter (26409): #13     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:118)
E/flutter (26409): #14     RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:165)
E/flutter (26409): #15     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:118)
E/flutter (26409): #16     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1863)
E/flutter (26409): #17     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:118)
E/flutter (26409): #18     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1863)
E/flutter (26409): #19     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:118)
E/flutter (26409): #20     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1863)
E/flutter (26409): #21     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:118)
E/flutter (26409): #22     RenderCustomPaint.hitTestChildren (package:flutter/src/rendering/custom_paint.dart:500)
E/flutter (26409): #23     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1863)
E/flutter (26409): #24     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:118)
E/flutter (26409): #25     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1863)
E/flutter (26409): #26     _RenderFlex&RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:2190)
E/flutter (26409): #27     RenderFlex.hitTestChildren (package:flutter/src/rendering/flex.dart:925)
E/flutter (26409): #28     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1863)
E/flutter (26409): #29     _RenderCustomMultiChildLayoutBox&RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:2190)
E/flutter (26409): #30     RenderCustomMultiChildLayoutBox.hitTestChildren (package:flutter/src/rendering/custom_layout.dart:365)
E/flutter (26409): #31     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1863)
E/flutter (26409): #32     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:118)
E/flutter (26409): #33     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1863)
E/flutter (26409): #34     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:118)
E/flutter (26409): #35     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1863)
E/flutter (26409): #36     RenderPhysicalMode
```

### flutter doctor

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.5.1, on Microsoft Windows [Version 10.0.17134.228], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.0-rc2)
[√] Android Studio (version 3.1)
[√] IntelliJ IDEA Community Edition (version 2018.1)
[√] Connected devices (1 available)

• No issues found!
```

### Workarounds already done
1. Use NeverScrollablePhysics for tab bar.

**Comment by JeffersonCarvalh0** [comment]
I'm experiencing a similar issue here, but in my case, it does not show any error message.The swipe between tabs simply don't work when I try to do it in the area of the slidable widgets, and it happens both in debug and release modes. Also, I'm using `NestedScrollView` instead of `TabBarView`

**Comment by letsar** [comment]
You cannot use `Slidable` in a `TabView` with the same scroll direction. How can we know if you want to swipe the `Slidable` or the page?
