### ISSUE TITLE
keepAlive Issue on Redux ListView-ListTile

### ISSUE THREAD

**Issue by ejabu** [letsar/flutter_slidable#29]
This is the error log

```
V/BoostFramework(15064): BoostFramework() : mPerf = com.qualcomm.qti.Performance@255afe2
I/flutter (15064): ══╡ EXCEPTION CAUGHT BY ANIMATION LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (15064): The following NoSuchMethodError was thrown while notifying status listeners for AnimationController:
I/flutter (15064): The getter 'keepAlive' was called on null.
I/flutter (15064): Receiver: null
I/flutter (15064): Tried calling: keepAlive
I/flutter (15064):
I/flutter (15064): When the exception was thrown, this was the stack:
I/flutter (15064): #0      KeepAlive.applyParentData (package:flutter/src/widgets/sliver.dart:1033)
I/flutter (15064): #1      RenderObjectElement._updateParentData (package:flutter/src/widgets/framework.dart:4509)
I/flutter (15064): #2      ParentDataElement._applyParentData.applyParentDataToChild (package:flutter/src/widgets/framework.dart:3973)
I/flutter (15064): #3      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3688)
I/flutter (15064): #4      ParentDataElement._applyParentData.applyParentDataToChild (package:flutter/src/widgets/framework.dart:3976)
I/flutter (15064): #5      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3688)
I/flutter (15064): #6      ParentDataElement._applyParentData (package:flutter/src/widgets/framework.dart:3979)
I/flutter (15064): #7      ParentDataElement.applyWidgetOutOfTurn (package:flutter/src/widgets/framework.dart:4018)
I/flutter (15064): #8      _AutomaticKeepAliveState._updateParentDataOfChild (package:flutter/src/widgets/automatic_keep_alive.dart:135)
I/flutter (15064): #9      _AutomaticKeepAliveState._addClient (package:flutter/src/widgets/automatic_keep_alive.dart:86)
I/flutter (15064): #10     NotificationListener._dispatch (package:flutter/src/widgets/notification_listener.dart:125)
I/flutter (15064): #11     Notification.visitAncestor (package:flutter/src/widgets/notification_listener.dart:45)
I/flutter (15064): #12     Element.visitAncestorElements (package:flutter/src/widgets/framework.dart:3307)
I/flutter (15064): #13     Notification.dispatch (package:flutter/src/widgets/notification_listener.dart:59)
I/flutter (15064): #14     _SlidableState&State&TickerProviderStateMixin&AutomaticKeepAliveClientMixin._ensureKeepAlive (package:flutter/src/widgets/automatic_keep_alive.dart:345)
I/flutter (15064): #15     _SlidableState&State&TickerProviderStateMixin&AutomaticKeepAliveClientMixin.updateKeepAlive (package:flutter/src/widgets/automatic_keep_alive.dart:366)
I/flutter (15064): #16     SlidableState._handleShowAllActionsStatusChanged (package:flutter_slidable/src/widgets/slidable.dart:996)
I/flutter (15064): #17     _AnimationController&Animation&AnimationEagerListenerMixin&AnimationLocalListenersMixin&AnimationLocalStatusListenersMixin.notifyStatusListeners (package:flutter/src/animation/listener_helpers.dart:161)
I/flutter (15064): #18     AnimationController._checkStatusChanged (package:flutter/src/animation/animation_controller.dart:588)
I/flutter (15064): #19     AnimationController._startSimulation (package:flutter/src/animation/animation_controller.dart:532)
I/flutter (15064): #20     AnimationController.animateWith (package:flutter/src/animation/animation_controller.dart:519)
I/flutter (15064): #21     AnimationController.fling (package:flutter/src/animation/animation_controller.dart:507)
I/flutter (15064): #22     SlidableState.close (package:flutter_slidable/src/widgets/slidable.dart:906)
I/flutter (15064): #23     SlidableState._isScrollingListener (package:flutter_slidable/src/widgets/slidable.dart:928)
I/flutter (15064): #24     ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:161)
I/flutter (15064): #25     ValueNotifier.set:value (package:flutter/src/foundation/change_notifier.dart:217)
I/flutter (15064): #26     ScrollPosition.beginActivity (package:flutter/src/widgets/scroll_position.dart:617)
I/flutter (15064): #27     ScrollPositionWithSingleContext.beginActivity (package:flutter/src/widgets/scroll_position_with_single_context.dart:117)
I/flutter (15064): #28     ScrollPositionWithSingleContext.goBallistic (package:flutter/src/widgets/scroll_position_with_single_context.dart:149)
I/flutter (15064): #29     IdleScrollActivity.applyNewDimensions (package:flutter/src/widgets/scroll_activity.dart:149)
I/flutter (15064): #30     ScrollPosition.applyNewDimensions (package:flutter/src/widgets/scroll_position.dart:485)
I/flutter (15064): #31     ScrollPositionWithSingleContext.applyNewDimensions (package:flutter/src/widgets/scroll_position_with_single_context.dart:107)
I/flutter (15064): #32     ScrollPosition.applyContentDimensions (package:flutter/src/widgets/scroll_position.dart:456)
I/flutter (15064): #33     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1242)
I/flutter (15064): #34     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1438)
I/flutter (15064): #35     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:697)
I/flutter (15064): #36     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:270)
I/flutter (15064): #37     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:654)
I/flutter (15064): #38     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208)
I/flutter (15064): #39     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990)
I/flutter (15064): #40     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930)
I/flutter (15064): #41     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842)
I/flutter (15064): #42     _invoke (dart:ui/hooks.dart:128)
I/flutter (15064): #43     _drawFrame (dart:ui/hooks.dart:117)
I/flutter (15064):
I/flutter (15064): The AnimationController notifying status listeners was:
I/flutter (15064):   AnimationController#0cb7b(◀ 0.000)
I/flutter (15064): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (15064): Another exception was thrown: NoSuchMethodError: The getter 'keepAlive' was called on null.
I/flutter (15064): Another exception was thrown: NoSuchMethodError: The getter 'keepAlive' was called on null.
I/flutter (15064): Another exception was thrown: NoSuchMethodError: The getter 'keepAlive' was called on null.
I/flutter (15064): Another exception was thrown: NoSuchMethodError: The getter 'keepAlive' was called on null.
I/flutter (15064): Another exception was thrown: NoSuchMethodError: The getter 'keepAlive' was called on null.
I/flutter (15064): Another exception was thrown: NoSuchMethodError: The getter 'keepAlive' was called on null.
I/flutter (15064): Another exception was thrown: NoSuchMethodError: The getter 'keepAlive' was called on null.
I/flutter (15064): Another exception was thrown: NoSuchMethodError: The getter 'keepAlive' was called on null.
I/flutter (15064): Another exception was thrown: NoSuchMethodError: The getter 'keepAlive' was called on null.
I/flutter (15064): Another exception was thrown: NoSuchMethodError: The getter 'keepAlive' was called on null.
I/flutter (15064): Another exception was thrown: NoSuchMethodError: The getter 'keepAlive' was called on null.
I/flutter (15064): Another exception was thrown: NoSuchMethodError: The getter 'keepAlive' was called on null.
I/flutter (15064): Another exception was thrown: NoSuchMethodError: The getter 'keepAlive' was called on null.
I/flutter (15064): Another exception was thrown: NoSuchMethodError: The getter 'keepAlive' was called on null.
I/flutter (15064): Another exception was thrown: NoSuchMethodError: The getter 'keepAlive' was called on null.
I/flutter (15064): Another exception was thrown: NoSuchMethodError: The getter 'keepAlive' was called on null.
I/flutter (15064): Another exception was thrown: NoSuchMethodError: The getter 'keepAlive' was called on null.
I/flutter (15064): Another exception was thrown: NoSuchMethodError: The getter 'keepAlive' was called on null.
I/flutter (15064): Another exception was thrown: NoSuchMethodError: The getter 'keepAlive' was called on null.
I/flutter (15064): Another exception was thrown: NoSuchMethodError: The getter 'keepAlive' was called on null.
I/flutter (15064): Another exception was thrown: NoSuchMethodError: The getter 'keepAlive' was called on null.
I/flutter (15064): Another exception was thrown: NoSuchMethodError: The getter 'keepAlive' was called on null.
I/flutter (15064): Another exception was thrown: NoSuchMethodError: The getter 'keepAlive' was called on null.
I/flutter (15064): Another exception was thrown: NoSuchMethodError: The getter 'keepAlive' was called on null.
I/flutter (15064): Another exception was thrown: NoSuchMethodError: The getter 'keepAlive' was called on null.
I/flutter (15064): Another exception was thrown: NoSuchMethodError: The getter 'keepAlive' was called on null.
I/flutter (15064): Another exception was thrown: NoSuchMethodError: The getter 'keepAlive' was called on null.
I/flutter (15064): Another exception was thrown: NoSuchMethodError: The getter 'keepAlive' was called on null.
I/flutter (15064): Another exception was thrown: NoSuchMethodError: The getter 'keepAlive' was called on null.
I/flutter (15064): Another exception was thrown: NoSuchMethodError: The getter 'keepAlive' was called on null.
I/flutter (15064): Another exception was thrown: NoSuchMethodError: The getter 'keepAlive' was called on null.
I/flutter (15064): Another exception was thrown: NoSuchMethodError: The getter 'keepAlive' was called on null.
I/flutter (15064): Another exception was thrown: NoSuchMethodError: The getter 'keepAlive' was called on null.
I/flutter (15064): Another exception was thrown: NoSuchMethodError: The getter 'keepAlive' was called on null.
I/flutter (15064): Another exception was thrown: NoSuchMethodError: The getter 'keepAlive' was called on null.
I/flutter (15064): Another exception was thrown: NoSuchMethodError: The getter 'keepAlive' was called on null.
I/flutter (15064): Another exception was thrown: NoSuchMethodError: The getter 'keepAlive' was called on null.
I/flutter (15064): Another exception was thrown: NoSuchMethodError: The getter 'keepAlive' was called on null.
I/flutter (15064): Another exception was thrown: NoSuchMethodError: The getter 'keepAlive' was called on null.
I/flutter (15064): Another exception was thrown: NoSuchMethodError: The getter 'keepAlive' was called on null.
I/flutter (15064): Another exception was thrown: NoSuchMethodError: The getter 'keepAlive' was called on null.
I/flutter (15064): Another exception was thrown: NoSuchMethodError: The getter 'keepAlive' was called on null.
I/flutter (15064): Another exception was thrown: NoSuchMethodError: The getter 'keepAlive' was called on null.
I/flutter (15064): Another exception was thrown: NoSuchMethodError: The getter 'keepAlive' was called on null.
I/flutter (15064): Another exception was thrown: NoSuchMethodError: The getter 'keepAlive' was called on null.
I/flutter (15064): Another exception was thrown: NoSuchMethodError: The getter 'keepAlive' was called on null.
I/flutter (15064): Another exception was thrown: NoSuchMethodError: The getter 'keepAlive' was called on null.
I/flutter (15064): Another exception was thrown: NoSuchMethodError: The getter 'keepAlive' was called on null.
I/flutter (15064): Another exception was thrown: NoSuchMethodError: The getter 'keepAlive' was called on null.
I/flutter (15064): Another exception was thrown: NoSuchMethodError: The getter 'keepAlive' was called on null.
I/flutter (15064): Another exception was thrown: NoSuchMethodError: The getter 'keepAlive' was called on null.
I/flutter (15064): Another exception was thrown: NoSuchMethodError: The getter 'keepAlive' was called on null.
I/flutter (15064): Another exception was thrown: NoSuchMethodError: The getter 'keepAlive' was called on null.
I/flutter (15064): Another exception was thrown: NoSuchMethodError: The getter 'keepAlive' was called on null.
I/flutter (15064): Another exception was thrown: NoSuchMethodError: The getter 'keepAlive' was called on null.
I/flutter (15064): Another exception was thrown: NoSuchMethodError: The getter 'keepAlive' was called on null.
I/flutter (15064): Another exception was thrown: NoSuchMethodError: The getter 'keepAlive' was called on null.
I/flutter (15064): Another exception was thrown: NoSuchMethodError: The getter 'keepAlive' was called on null.
I/flutter (15064): Another exception was thrown: NoSuchMethodError: The getter 'keepAlive' was called on null.
I/flutter (15064): Another exception was thrown: NoSuchMethodError: The getter 'keepAlive' was called on null.
I/flutter (15064): Another exception was thrown: NoSuchMethodError: The getter 'keepAlive' was called on null.
I/flutter (15064): Another exception was thrown: NoSuchMethodError: The getter 'keepAlive' was called on null.
I/flutter (15064): Another exception was thrown: NoSuchMethodError: The getter 'keepAlive' was called on null.
I/flutter (15064): Another exception was thrown: NoSuchMethodError: The getter 'keepAlive' was called on null.
I/flutter (15064): Another exception was thrown: NoSuchMethodError: The getter 'keepAlive' was called on null.
I/flutter (15064): Another exception was thrown: NoSuchMethodError: The getter 'keepAlive' was called on null.
I/flutter (15064): Another exception was thrown: NoSuchMethodError: The getter 'keepAlive' was called on null.
I/flutter (15064): Another exception was thrown: NoSuchMethodError: The getter 'keepAlive' was called on null.
I/flutter (15064): Another exception was thrown: NoSuchMethodError: The getter 'keepAlive' was called on null.
I/flutter (15064): Another exception was thrown: NoSuchMethodError: The getter 'keepAlive' was called on null.
I/flutter (15064): Another exception was thrown: NoSuchMethodError: The getter 'keepAlive' was called on null.
I/flutter (15064): Another exception was thrown: NoSuchMethodError: The getter 'keepAlive' was called on null.
I/flutter (15064): Another exception was thrown: NoSuchMethodError: The getter 'keepAlive' was called on null.
I/flutter (15064): Another exception was thrown: NoSuchMethodError: The getter 'keepAlive' was called on null.
I/flutter (15064): Another exception was thrown: NoSuchMethodError: The getter 'keepAlive' was called on null.





```

**Comment by ejabu** [comment]
I made repository here https://github.com/ejabu/slidable_redux_flutter
![screenshot_2018-09-08-10-06-36-143_com example slidable redux](https://user-images.githubusercontent.com/2019630/45250089-97caa680-b356-11e8-826e-6cb930c79967.png)

**Comment by letsar** [comment]
Hi @ejabu thanks for the repo, I'am going to look at this.

**Comment by letsar** [comment]
This is indeed related to https://github.com/flutter/flutter/issues/11895.
If you change the Slidable by a simple TextField, you end up with the same issue.
```dart
return TextField(
  key: Key(widget.todo.id),
);
```

I reduced the possibilities for this to happen with the `Slidable` widget. I will published my pseudo-fix today.

**Comment by letsar** [comment]
Can you test with the 0.4.6 version I've just published?
If the `closeOnScroll` parameter is true (the default), this error should not happen.

**Comment by ejabu** [comment]
btw is it okay for me to close this issue ? I don't know whethers it should be the issuer or the owner of the repo who is privileged to do this..

**Comment by letsar** [comment]
No it's good to me that you closed the issue 👍
